apiVersion: batch/v1
kind: Job
metadata:
  name: webapp
  namespace: producer
spec: 
  template:
    spec:
      containers:
      - name: webapp-cve-processor
        image: "{{ .Values.image.docker_repo }}:{{ .Values.image.webapp }}-{{ .Values.image.webapp_version }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: postgres-config

      restartPolicy: Never

  backoffLimit: 5
