apiVersion: batch/v1
kind: Job
metadata:
  name: webapp
spec: 
  template:
    spec:
      containers:
      - name: webapp-cve-processor
        image: "{{ .Values.image.docker_repo }}:{{ .Values.image.webapp }}-{{ .Values.image.webapp_version }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: postgres-config

      initContainers:
      - name: delay-start
        image: busybox
        command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for DB service"
              sleep 30
      - name: flyway-init
        image: "{{ .Values.image.docker_repo }}:{{ .Values.image.pg_container }}-{{ .Values.image.pg_container_version }}"
        imagePullPolicy: Always
        command:
        - "/bin/sh"
        - "-c"
        - "flyway -user={{ .Values.postgres.user }} -password={{ .Values.postgres.password }} -url={{ .Values.postgres.url }} migrate"
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never

  backoffLimit: 5
