apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-config
data:
  POSTGRES_DB: "{{ .Values.postgres.dbname }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  PG_DATA: /data
  host: "{{ .Values.postgres.host }}"
  port: "{{ .Values.postgres.port }}"