apiVersion: v1
kind: Pod
metadata:
  name: pg-migration
  # labels:
  #   app.kubernetes.io/managed-by: "Helm"
  # annotations:
  #   meta.helm.sh/release-name: "{{ .Release.Name }}"
  #   meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  containers:
    - name: "webapp"
      image: "{{ .Values.image.docker_repo}}:{{ .Values.image.webapp}}"
  initContainers:
    - name: flyway-init
      image: "{{ .Values.image.docker_repo}}:{{ .Values.image.pg_container}}"
      command:
        - "/bin/sh"
        - "-c"
        - "flyway -user={{ .Values.postgres.user }} -password={{ .Values.postgres.password }} -url={{ .Values.postgres.url }} migrate"
      env:
        # Add any environment variables needed by Flyway here
      # Add any volume mounts needed by Flyway here
  imagePullSecrets:
  - name: regcred
