apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres

spec:
  serviceName: postgres
  #replicas: 0
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
        - name: postgres-dbdata
          mountPath: /data
      volumes:
      - name: postgres-dbdata
        persistentVolumeClaim:
          claimName: postgres-db-ebs-pvc 
